//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaloPolymer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataBase
    {
        public int id { get; set; }
        public Nullable<int> idCeh { get; set; }
        public Nullable<int> idASYTP { get; set; }
        public Nullable<int> idEquipmentType { get; set; }
        public string Name_Equipment { get; set; }
        public string Name_Network { get; set; }
        public string Number_Serial { get; set; }
        public string Number_Inventory { get; set; }
        public string IP_address { get; set; }
        public string Time_Synchron { get; set; }
        public string Mac_address { get; set; }
        public string VLAN { get; set; }
        public string Manufacturer { get; set; }
        public string Network_card { get; set; }
    
        public virtual ASYTP ASYTP { get; set; }
        public virtual Ceh Ceh { get; set; }
        public virtual EquipmentType EquipmentType { get; set; }
    }
}
